app/main/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
# -*- coding: utf-8 -*-

from datetime import datetime

from flask import abort, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from sqlalchemy import desc
from sqlalchemy.exc import IntegrityError

from app import db
from app.main import bp
from app.models import Org, Terrorist


@bp.route('/')
@bp.route('/index')
def index():
    """Show main page."""
    # Terrorists data
    t_count = Terrorist.query.count()
    # Organization data
    o_count = Org.query.count()

    return render_template('main.html', t_count=t_count, o_count=o_count)


@bp.route('/persons')
def persons():
    """Show just persons."""

    page = request.args.get('page', 1, type=int)

    ters = db.session.query(
            Terrorist
        ).order_by(
            desc(Terrorist.created)
        ).paginate(page, 30, False)

    next_url = url_for('main.persons', page=ters.next_num) if ters.has_next else None
    prev_url = url_for('main.persons', page=ters.prev_num) if ters.has_prev else None

    return render_template(
            'persons.html', ters=ters.items, next_url=next_url,
            prev_url=prev_url
        )


@bp.route('/orgs')
def orgs():
    """Show just orgs."""
    page = request.args.get('page', 1, type=int)

    orgs = db.session.query(
            Org
        ).order_by(
            desc(Org.created)
        ).paginate(page, 30, False)

    next_url = url_for('main.orgs', page=orgs.next_num) if orgs.has_next else None
    prev_url = url_for('main.orgs', page=orgs.prev_num) if orgs.has_prev else None

    return render_template(
            'orgs.html', orgs=orgs.items, next_url=next_url, prev_url=prev_url
        )

app/templates/api_doc.html
{% extends "base.html" %}
{% block content %}

<h3>API</h3>
<h5>ОПИСАНИЕ</h5>
<p>API реализована с использованием архитектурного паттерна REST, т.е. для взаимодействия с API необходимо отправлять запросы посредством http протокола на указанные ниже URL.</p>
<p>В данной версии API возможны только <code>GET</code> запросы. Результат запроса будет возвращен в виде <code>JSON</code> формата.</p>

<h5>АВТОРИЗАЦИЯ</h5>
<p>Авторизация отсутствует</p>

<h5>РЕСУРСЫ</h5>

<p>Для поиска физических лиц: <code>{{ ept }}</code></p>
<p>Для поиска организаций: <code>{{ epo }}</code></p>

<h5>ПРАВИЛА ФОРМИРОВАНИЯ ЗАПРОСОВ</h5>
<p>Аргументы для запроса необходимо передавать в виде параментов</p>

<h6>ПОИСК ФИЗИЧЕСКИХ ЛИЦ</h6>
<p>Поиск физических лиц возможен <strong>только</strong> по <strong>ИИН</strong> или <strong>фамилии и имени</strong> по <strong>строгому совпадению</strong>.</p>
<p>Пример запроса по <strong>ИИН</strong> <em>781003302869</em></p>
<pre><code>{{ ept }}?iin=781003302869</code></pre>

<p>Пример ответа:</p>
<pre><code>
[
    {
        "birthdate": "1978-10-03",
        "created": "2018-06-20T04:36:15.539726",
        "excluded": null,
        "fname": "МУРАТ",
        "id": 1317,
        "iin": "781003302869",
        "included": "2018-06-04",
        "lname": "СМАГУЛОВ",
        "mname": "МАНАТОВИЧ"
    }
]
</code></pre>

<p>Пример запроса по <strong>фамилии</strong> <em>АБДУБАЙТОВ</em> <strong>и имени</strong> <em>АСЫЛЖАн</em>.</p>
<pre><code>{{ ept }}?lname=АБДУБАЙТОВ&fname=АСЫЛЖАн</code></pre>

<p>Пример ответа:</p>
<pre><code>
[
    {
        "birthdate": "1987-05-03",
        "created": "2018-06-20T04:36:15.348606",
        "excluded": null,
        "fname": "АСЫЛЖАН",
        "id": 10,
        "iin": "870530302880",
        "included": null,
        "lname": "АБДУБАЙТОВ",
        "mname": "САПАРХАНОВИЧ"
    }
]
</code></pre>

<h6>ПОИСК ОРГАНИЗАЦИЙ</h6>
<p>Поиск организаций возможен <strong>только</strong> по <strong>наименованию</strong> по <strong>строгому совпадению</strong>.</p>

<p>Пример запроса по наименованию <em>НЕЗАРЕГИСТРИРОВАННОЕ ОБЩЕСТВЕННОЕ ОБЪЕДИНЕНИЕ «НАРОДНАЯ ПАРТИЯ АЛГА»</em></p>
<pre><code>{{ epo }}?name=НЕЗАРЕГИСТРИРОВАННОЕ ОБЩЕСТВЕННОЕ ОБЪЕДИНЕНИЕ «НАРОДНАЯ ПАРТИЯ АЛГА»</code></pre>

<p>Пример ответа:</p>
<pre><code>
[
    {
        "created": "2018-06-20T04:36:18.247305",
        "excluded": null,
        "id": 24,
        "included": "2018-04-17",
        "name": "НЕЗАРЕГИСТРИРОВАННОЕ ОБЩЕСТВЕННОЕ ОБЪЕДИНЕНИЕ «НАРОДНАЯ ПАРТИЯ АЛГА»",
        "name_eng": null
    }
]
</code></pre>

<h6>ОШИБКИ ЗАПРОСА</h6>
<p>Если запрос сформирован неверно, то вернется сообщение в <code>JSON</code> формате с текстом и кодом ошибки.</p>

<p>Пример неверного запроса</p>
<pre><code>{{ epo }}?lname=АБДУБАЙТОВ</code></pre>

<p>Пример ответа:</p>
<pre><code>
{
    "error": "Bad Request",
    "error_code": 400,
    "message": "parameters iin or lname and fname must be in request"
}
</code></pre>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Frienly list of terrorists in RK</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/skeleton.css') }}">

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>

  <div class="container">

  {% include 'header.html' %}

  {% block content %}
  {% endblock %}
  </div>

</body>
</html>

app/templates/header.html
<h3>Перечень организаций и лиц, связанных с финансированием терроризма и экстремизма</h3>
<h5>Источником данных служит <a href="http://kfm.gov.kz/ru/the-list-of-organizations-and-individuals-associa/">КФМ РК</a></h5>
<p>Все вопросы и замечания по наполнению списка адресуйте в КФМ РК. Данный русурс служит <strong>только</strong> для удобного доступа к данным, который не может обеспечить КФМ.</p>
<hr>
<h5>Разделы</h5>
<div class="row">
    <ul class="pages">
        <li><a href=" {{ url_for('main.index') }} ">Главная</a></li>
        <li><a href=" {{ url_for('main.persons') }} ">Физические лица</a></li>
        <li><a href=" {{ url_for('main.orgs') }} ">Организации</a></li>
        <li><a href=" {{ url_for('api.api_doc') }} ">API</a></li>
    </ul>
</div>

<hr>

app/templates/main.html
{% extends "base.html" %}

{% block content %}
<h5>Статистика</h5>
<table class="u-full-width">
    <thead>
        <tr>
          <th>Объекты</th>
          <th>Количество</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Физические лица</td>
            <td>{{ t_count }}</td>
        </tr>
        <tr>
            <td>Организации</td>
            <td>{{ o_count }}</td>
        </tr>
    </tbody>
</table>

{% endblock %}

app/templates/orgs.html
{% extends "base.html" %}
{% block content %}
<h5>Организации</h5>
<div class="row">
    <table class="u-full-width">
        <thead>
            <tr>
                <th>Создан</th>
                <th>Название</th>
                <th>Название(альт)</th>
                <th>Включен</th>
                <th>Исключен</th>
            </tr>
        </thead>
        <tbody>
            {% for org in orgs %}
            <tr>
                <td>{{ org.created_fancy() }}</td>
                <td>{{ org.name }} </td>
                <td>{% if org.name_eng %}{{ org.name_eng }}{% endif %}</td>
                <td>{% if org.included_fancy() %}{{ org.included_fancy() }}{% endif %}</td>
                <td>{% if org.excluded_fancy() %}{{ org.excluded_fancy() }}{% endif %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="row">
    <div class="six columns">
        {% if prev_url %}
            <a href="{{ prev_url }}">Влево</a>
        {% endif %}
    </div>
    <div class="six columns">
        {% if next_url %}
            <a class="u-pull-right" href="{{ next_url }}">Вправо</a>
        {% endif %}
    </div>
</div>

<hr>

{% endblock %}

app/templates/persons.html
{% extends "base.html" %}
{% block content %}

<h5>Физические лица</h5>
<div class="row">
    <table class="u-full-width">
        <thead>
            <tr>
                <th>Создан</th>
                <th>Фамилия</th>
                <th>Имя</th>
                <th>Отчество</th>
                <th>ИИН</th>
                <th>ДР</th>
                <th>Включен</th>
                <th>Исключен</th>
            </tr>
        </thead>
        <tbody>
            {% for ter in ters %}
              <tr>
                <td>{{ ter.created_fancy() }}</td>
                <td>{{ ter.lname }}</td>
                <td>{{ ter.fname }}</td>
                <td>{% if ter.mname %}{{ ter.mname }}{% endif %}</td>
                <td>{% if ter.iin %}{{ ter.iin }}{% endif %}</td>
                <td>{% if ter.birthdate_fancy() %}{{ ter.birthdate_fancy() }}{% endif %}</td>
                <td>{% if ter.included_fancy() %}{{ ter.included_fancy() }}{% endif %}</td>
                <td>{% if ter.excluded_fancy() %}{{ ter.excluded_fancy() }}{% endif %}</td>
              </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="row">
    <div class="six columns">
        {% if prev_url %}
          <a href="{{ prev_url }}">Влево</a>
        {% endif %}
    </div>
    <div class="six columns">
        {% if next_url %}
            <a class="u-pull-right" href="{{ next_url }}">Вправо</a>
        {% endif %}
    </div>
</div>

<hr>
{% endblock %}